matrix:
  include:
    - os: linux
      language: node_js
      node_js: "13"

cache:
  directories:
    - node_modules

script:
  - yarn
  - CI=true yarn test --passWithNoTests --ci
  - yarn build
  - touch build/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  target-branch: gh-pages
  local-dir: build
  github-token: $GITHUB_TOKEN
  on:
    branch: master